version: '3'

services:
  db-cust:
    image: abhishek050990/customer-db:1.0
    container_name: con-db-cust
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "6033:3306"
  phpmyadmin-cust:
    image: phpmyadmin/phpmyadmin
    container_name: con-pma-cust
    depends_on:
      - db-cust
    environment:
      PMA_HOST: con-db-cust
    ports:
      - 8081:80
  db-sales:
    image: abhishek050990/sales-db:1.0
    container_name: con-db-sales
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "6034:3306"
  phpmyadmin-sales:
    image: phpmyadmin/phpmyadmin
    container_name: con-pma-sales
    depends_on:
      - db-sales
    environment:
      PMA_HOST: con-db-sales
    ports:
      - 8082:80
  db-inventory:
    image: abhishek050990/inventory-db:1.0
    container_name: con-db-inventory
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "6035:3306"
  phpmyadmin-inventory:
    image: phpmyadmin/phpmyadmin
    container_name: con-pma-inventory
    depends_on:
      - db-inventory
    environment:
      PMA_HOST: con-db-inventory
    ports:
      - 8083:80
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: con-zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: con-kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_LISTENERS: LISTENER_INTERNAL://kafka:29092,LISTENER_EXTERNAL://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://kafka:29092,LISTENER_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topic_update_sale:1:1,topic_register_new_customer:1:1"
#      KAFKA_ADVERTISED_HOST_NAME: kafka,localhost
#      KAFKA_ADVERTISED_PORT: 9092
    # config/docker-compose.yml
#  kafka:
#    image: docker.io/bitnami/kafka:3
#    ports:
#      - "29092:29092"
#      - "9092:9092"
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
#      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:29092
#      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:29092
#      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
#    depends_on:
#      - zookeeper
