apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-db-deployment
  namespace: kafka
  labels:
    app: customer-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-db
  template:
    metadata:
      labels:
        app: customer-db
    spec:
      containers:
        - name: customer-db
          image: abhishek050990/customer-db:1.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
---
apiVersion: v1
kind: Service
metadata:
  name: customer-db-service
  namespace: kafka
spec:
  selector:
    app: customer-db
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 6033
      targetPort: 3306
      nodePort: 30033
