server:
  port: 9081
db:
  url: localhost:6033
  dbName: pos-customer
  username: root
  password: root
kafka:
  consumer:
    url: kafka:9092
spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://${db.url}/${db.dbName}
    username: ${db.username}
    password: ${db.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show-sql: true
        use_sql_comments: true
  kafka:
    consumer:
      bootstrap-servers: ${kafka.consumer.url}
      group-id: consumer-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
logging:
  level:
    org:
      hibernate:
        type: trace