server:
  port:  9082
db:
  url: localhost:6035
  dbName: pos-inventory
  username: root
  password: root
spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://${db.url}/${db.dbName}
    username: ${db.username}
    password: ${db.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show-sql: true