apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-app-config
  namespace: customer
data:
  kafka-consumer-url: kafka-service.kafka.svc.cluster.local:9092
  customer-db-url: customer-db-service:6033
